### ISSUE TITLE
some cleanup needed in amba_case_study.tlsf

### ISSUE THREAD

**Issue by adl** [SYNTCOMP/benchmarks#13]
At the end `benchmarks/tlsf/amba/parametric/amba_case_study.tlsf` there is still
```
//#!SYNTCOMP
//REF_SIZE : 0
//#.
```

This causes `genParametric.py` to produce files ending with:
```
//#!SYNTCOMP
//REF_SIZE : 0
//#.
//#!SYNTCOMP
//STATUS : unknown
//REF_SIZE : 0
//#
```
(I discovered that while trying to understand why `amba_case_study_2.tlsf` in SyntComp 2021, produce `Error=Unknown status value`.  But it's actually unrelated: the `amba_case_study_2.tlsf` from this year is not parametric and was just missing the status specification.)

**Comment by 5nizza** [comment]
Thanks, I removed those tags.

But this is actually a part of the bigger problem: currently the benchmarks, their statuses, and the scripts to select benchmarks -- all these is mixed in the same repository. As a result, there are unnecessary folders like `parametric` and `csv` files that do not belong much here. (OK, `csv` files may stay, _if_ they provide realisability statuses and model sizes and who-solved-it, but folders `parametric` should definitely go away.) This requires overhauling of the benchmark-processing scripts. I created issue #14 for that.
