### ISSUE TITLE
Add Keiren's parity-game benchmarks

### ISSUE THREAD

**Issue by gaperez64** [SYNTCOMP/benchmarks#15]
See here: https://arxiv.org/pdf/1407.3121.pdf

**Comment by trolando** [comment]
https://figshare.com/articles/dataset/Parity_games/6004130/1

**Comment by gaperez64** [comment]
I added as many as I could translate within a reasonable amount of time and memory: a9ca6a525866dd13fdf0968c9824c204edc8b4b7
