### ISSUE TITLE
LTLf track benchmarks

### ISSUE THREAD

**Issue by Shufang-Zhu** [SYNTCOMP/benchmarks#24]
The archive includes benchmarks and a readme.md.
https://drive.google.com/file/d/1LYsvcOevyDkv6Kb3EgdGFLWrQmg9rhvo/view?usp=sharing

**Comment by gaperez64** [comment]
Done. Thanks @Shufang-Zhu !

A few datasets look parametric to me, I'll add an issue to make them TLSF-parametric for future editions of the competition.

**Comment by Shufang-Zhu** [comment]
Great!

**Comment by gaperez64** [comment]
I may have spoken too soon. Some benchmarks have a & (instead of && I suppose?), see attached log for examples. I am going to batch update them to && if you agree @Shufang-Zhu?

**Comment by gaperez64** [comment]
Nope, that does not work. For instance, `Random/Lydia/case_06_50/26.tlsf` is still broke afterwards.

**Comment by Shufang-Zhu** [comment]
Can you attach the version of `Random/Lydia/case_06_50/26.tlsf` after changing the single &'s to double ones?

**Comment by Shufang-Zhu** [comment]
> Nope, that does not work. For instance, `Random/Lydia/case_06_50/26.tlsf` is still broken after changing the single &'s to double ones.

Can you attach the version of Random/Lydia/case_06_50/26.tlsf after changing the single &'s to double ones? Thanks!

**Comment by Shufang-Zhu** [comment]
https://drive.google.com/file/d/11pLpzH08ErV-2Aqeo-cy1m426gqnm97a/view?usp=sharing
@gaperez64 please check the updated version of the benchmarks. Changing the single &'s to double ones still doesn't work, since sometimes, there is a left parenthesis right after &&, i.e., &&(, which leads to syntax error.

**Comment by gaperez64** [comment]
Yes, this version of the benchmarks is OK. I checked and `syfco` is able to process them all. Thanks for the quick fix @Shufang-Zhu!
