### ISSUE TITLE
Possible Semantic Issues with tlsf-fin

### ISSUE THREAD

**Issue by CoriolisSP** [SYNTCOMP/benchmarks#32]
Hello,

I've been exploring the SYNTCOMP rules page. According to the [Rules in LTL Categories](http://www.syntcomp.org/rules/) section, it is stated that, "_Like in the AIGER category, realizability is defined with respect to Mealy semantics, i.e., the outputs of the synthesized solutions can depend on the inputs without any delay. (Tools that only support Moore semantics can use a translation of the specification into Moore format, and then translate their solution into a Mealy machine.)_".

However, upon reading the LTLf-related track examples in the tlsf-fin directory of the SYNTCOMP benchmarks repository, it seems that the examples, such as [gfand01.tlsf](https://github.com/SYNTCOMP/benchmarks/blob/master/tlsf-fin/Patterns/GFand/gfand01.tlsf), demonstrate they are in Moore semantics.

Did I understand something wrong? Could you please provide some clarification?Thank you for your time and assistance in resolving this confusion.

Best Regards

**Comment by gaperez64** [comment]
Hi,

Good catch. Realizability and synthesis are defined with respect to the semantics in the tlsf file (see section 3 (here)[https://arxiv.org/pdf/2303.03839.pdf]). If your solver supports only one semantics, then you can use the syfco tool to translate benchmarks to the other one.

Guillermo
