### ISSUE TITLE
[TLSF] Keep only one instantiation of each benchmark

### ISSUE THREAD

**Issue by 5nizza** [SYNTCOMP/benchmarks#5]
Currently we have many instances of the same benchmark (e.g., `full_arbiter_2/3/4/5.tlsf`):
1. This increases repository size
2. If there is a bug, it needs to be fixed in all those instances
3. This requires creating a folder for each benchmark (e.g., we could keep almost all arbiters in one folder, but with those instances, we can't)

We can't just remove those instances (except a single representative) because we currently keep statistics for each instance in the benchmark file (at the end).

**Comment by 5nizza** [comment]
During the discussion, we concluded that it is better to
- keep stats separate from the benchmark source
- keep a single instance of each parameterized benchmark, and only in releases provide the full list of instances (i.e. provide instance for every `n` used)

**Comment by gaperez64** [comment]
This issue is partially resolved by merged pull request #11. What remains to be handled, as observed by @5nizza:
- the folder `tlsf/lift` contains three specs, all are parameterized
- the folder `tlsf/arbiters_zoo` contains 4 more specs, each is parameterized
- the folder `arbiters_s4` contain several benchmarks, all are parameterized
- the folder `amba` contains one parameterized benchmark

**Comment by meyerphi** [comment]
Just want to note (after observing some oddities for the benchmark selection on StarExec, but which are explained by #11): 

The directories `detector` and `generalized_buffer` both still contain several instances of the parameterized benchmark. Some of them are missing the `STATUS` line which causes the post-processor to fail, but anyway they should be removed.

Also `detector` is equivalent to `ltl2dba_C2`, up to renaming of atomic propositions, so depending on your policy for duplicates it could be removed completely (I see you removed the old `genbuf` files, which were actually syntactically slightly different from `generalized_buffer`).

**Comment by gaperez64** [comment]
Good catch @meyerphi, I have removed the instances that somehow survived the purge. @5nizza should we bring the `genbuf` files back?

**Comment by meyerphi** [comment]
@gaperez64 My opinion would to keep `genbuf` removed, both for a cleaner selection and as the specifications are hard to read (`genbuf6` even has a hard-to-spot typo and is actually unrealizable). However I can also see the value in keeping them for historical reasons, so I leave that decision to you.

**Comment by gaperez64** [comment]
This has been fixed in the latest commit.
