### ISSUE TITLE
Jarvis benchmarks

### ISSUE THREAD

**Issue by gaperez64** [SYNTCOMP/benchmarks#7]
@swenjacobs has now received the new benchmarks from Marvin Stenger, attached in the zip file. All of them are given in TSL and TLSF, and also come with the sources that would allow us to create new variants. It comes with some nice readme files that should make it self-explanatory.
[syntcomp__jarvis_benchmark_suite.zip](https://github.com/SYNTCOMP/benchmarks/files/6302552/syntcomp__jarvis_benchmark_suite.zip)

**Comment by 5nizza** [comment]
very cool! I will try to add them this week.
