### ISSUE TITLE
Syfco bug?

### ISSUE THREAD

**Issue by gaperez64** [SYNTCOMP/benchmarks#8]
Is it weird that the (e)hoa file for lilydemo01 puts everything conditional on there being a request?

See [here](https://github.com/SYNTCOMP/benchmarks/blob/a2397693197e23d30c92a9775e992588171471eb/parity/tlsf_based/lilydemo01.tlsf.ehoa#L2)

The tlsf file for lilydemo01 has 3 invariants. They can very well be in the scope of the same "always" but why in the same implication?

**Comment by 5nizza** [comment]
Calling SyFCo (v1.2.1.2) commands
- `syfco -f ltl -m fully ./lilidemo01.tlsf`
- `syfco -f ltl -m pretty ./lilidemo01.tlsf`
- `syfco -f acacia ./lilidemo01.tlsf`
all produce the correct answers. Which call did you use in your translation scripts?

(I checked with spot, the formula written in that HOA file is indeed the wrong formula)

**Comment by gaperez64** [comment]
I did `syfco --format ltlxba lilydemo01.tlsf`.

**Comment by gaperez64** [comment]
With the same output format, I think the attached file also gets mistranslated because Strix says it is realizable whereas in its original tlsf form it is unrealizable.

[full_arbiter_unreal1.tlsf.ehoa.txt](https://github.com/SYNTCOMP/benchmarks/files/6564909/full_arbiter_unreal1.tlsf.ehoa.txt)

**Comment by 5nizza** [comment]
> I did `syfco lilydemo01.tlsf --format ltlxba`.

```
$ syfco --version
SyFCo (v1.2.1.2)
The Synthesis Format Converter
```

```
$ syfco --format ltlxba lilydemo01.tlsf
G (req -> X (grant && X (grant && X grant)) && (grant -> X (! grant)) && (cancel -> X (! grant U go)))
```
The latter is correct.

**Comment by gaperez64** [comment]
it's correct if conjunction has higher precedence than implication right? could it be that it's Spot who's mixing things when this is taken as input? Because the automata for your formula and the one in the ehoa file look identical to me.

**Comment by 5nizza** [comment]
Oh, indeed, I see.
Then it is better to call syfco with `-m fully` then to ensure such mash-ups for priorities doesn't happen.

```
$ syfco --format ltlxba -m fully lilydemo01.tlsf
(G ((((req) -> (X ((grant) && (X ((grant) && (X (grant))))))) && ((grant) -> (X (! (grant))))) && ((cancel) -> (X ((! (grant)) U (go))))))
```

The original formula from my post:
```
G (req -> X (grant && X (grant && X grant)) && (grant -> X (! grant)) && (cancel -> X (! grant U go)))
```
assumes the implication `->` has a _higher_ precedence than the conjunction `&&`. I guess that is the format rules of `ltlxba`, so `syfco` does it correctly. But in SPOT, the conjunction `&` has a higher priority than `->`.

**Comment by gaperez64** [comment]
Great! Thanks for the feedback @5nizza. I'll try to report this to the Spot guys, I guess they might already know about it.

**Comment by 5nizza** [comment]
(but there is nothing to report? These are just two different formats: ltlxba format have one precedence rules while spot uses another? Anyway, you are welcome and have a nice weeeeeekend)
